# Generated by Django 6.0.2 on 2026-07-12 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_taskcategory_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktemplate',
            name='xp',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
