# Generated by Django 6.1.1 on 2026-09-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_tasktemplate_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='check_job_id',
            field=models.CharField(blank=True, db_index=True, help_text='Celery tekshiruv vazifasi ID si', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
